{
 "title": "Cluster Cache and Throughput Stats",
 "tags": [
  "isilon",
  "cluster"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "show tag values with key = \"cluster\""
   },
   {
    "name": "node",
    "label": "Node",
    "query": "show tag values with key = \"node\" where \"cluster\" =~ /^$cluster/"
   }
  ]
 },
 "panels": [
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Avg. Network Read Throughput",
   "type": "singlestat",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Reads",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster.net.ext.bytes.out.rate",
     "precision": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Avg. Network Write Throughput",
   "type": "singlestat",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Writes",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster.net.ext.bytes.in.rate",
     "precision": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    }
   ]
  },
  { "title": "Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "1m Load - $cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "repeat": "cluster",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Node $tag_node",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.load.1min",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com"
    }
   ]
  },
  {
   "title": "Open files and Active Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 }
  },
  {
   "title": "Open Files on $cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "$tag_cluster - Node $tag_node",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.open.files",
     "metric": "dfs.FSNamesystem.NumFilesUnderConstruction",
     "precision": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com"
    }
   ]
  },
  {
   "title": "Active HDFS Connections per Node on $cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "$tag_cluster Node $tag_node",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.clientstats.active.hdfs",
     "metric": "rpc.rpc.client.NumOpenConnections",
     "precision": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com"
    }
   ]
  },
  {
   "title": "Total File Operations & Capacity Used",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 }
  },
  {
   "title": "Total File Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "$tag_cluster Writes",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ifs.ops.in.rate",
     "metric": "dfs.namenode.TotalFileOps",
     "precision": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "rate"
    },
    {
     "aggregator": "avg",
     "alias": "$tag_cluster Reads",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ifs.ops.out.rate",
     "metric": "dfs.namenode.TotalFileOps",
     "precision": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "rate"
    }
   ]
  },
  {
   "title": "Capacity Cluster Wide",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Bytes Used",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ifs.bytes.used",
     "metric": "dfs.FSNamesystem.CapacityUsedGB",
     "precision": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com"
    },
    {
     "aggregator": "avg",
     "alias": "Bytes Available",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ifs.bytes.total",
     "metric": "dfs.FSNamesystem.CapacityTotalGB",
     "precision": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com"
    }
   ]
  },
  { "title": "L1 Cache Efficiency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "L1 Cache",
   "type": "text",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 38 },
   "content": "# L1 Cache\nOr Level 1 cache is a client side cache that caches file objects as they are accessed on that particular node."
  },
  {
   "title": "L1 Cache - $cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 22, "x": 2, "y": 38 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Data",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l1",
     "precision": "default",
     "query": "SELECT max(\"l1_data_read_hit\") /max(\"l1_data_read_start\") FROM \"node.ifs.cache\" WHERE \"cluster\" =~ /^$cluster$/ AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "Metadata",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l1",
     "precision": "default",
     "query": "SELECT max(\"l1_meta_read_hit\") /max(\"l1_meta_read_start\") FROM \"node.ifs.cache\" WHERE \"cluster\" =~ /^$cluster$/ AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    }
   ]
  },
  { "title": "L2 Cache Efficiency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "L2 Cache",
   "type": "text",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 46 },
   "content": "# L2 Cache\nLevel 2 cache is a back-end cache that caches file block that reside on that particular node."
  },
  {
   "title": "L2 Cache - $cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 22, "x": 2, "y": 46 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Data",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l1",
     "precision": "default",
     "query": "SELECT max(\"l2_data_read_hit\") /max(\"l2_data_read_start\") FROM \"node.ifs.cache\" WHERE \"cluster\" =~ /^$cluster$/ AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "Metadata",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l1",
     "precision": "default",
     "query": "SELECT max(\"l2_meta_read_hit\") /max(\"l2_meta_read_start\") FROM \"node.ifs.cache\" WHERE \"cluster\" =~ /^$cluster$/ AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    }
   ]
  },
  { "title": "L3 Cache Efficiency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "L3 Cache",
   "type": "text",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 54 },
   "content": "# L3 Cache\nLevel 3 cache is an SSD backed cache that works with L2 Cache and contains blocks and metadata that are local to that particular node."
  },
  {
   "title": "L3 Cache - $cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 22, "x": 2, "y": 54 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Data",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l1",
     "precision": "default",
     "query": "SELECT max(\"l3_data_read_hit\") /max(\"l3_data_read_start\") FROM \"node.ifs.cache\" WHERE \"cluster\" =~ /^$cluster$/ AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "Metadata",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l1",
     "precision": "default",
     "query": "SELECT max(\"l3_meta_read_hit\") /max(\"l3_meta_read_start\") FROM \"node.ifs.cache\" WHERE \"cluster\" =~ /^$cluster$/ AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    }
   ]
  },
  { "title": "L1 Metadata Cache by node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "L1 Metadata hits by node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 62 },
   "repeat": "cluster",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "L1 Read hits - node $tag_node",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.ifs.cache",
     "precision": "default",
     "query": "SELECT mean(\"l1_meta_read_hit\")/ mean(\"l1_meta_read_start\") FROM \"node.ifs.cache\" WHERE \"cluster\" =~ /^$cluster$/ AND \"node\" =~ /^$node$/ AND $timeFilter GROUP BY time($interval), \"node\", \"cluster\" fill(null)",
     "select": [
      [
       { "params": [ "l1_data_read_hit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ],
      [
       { "params": [ "l1_data_read_start" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    }
   ]
  },
  { "title": "L2 Metadata Cache by Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "L2 Metadata hits by node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 72 },
   "repeat": "cluster",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "L2 Read hits - node $tag_node",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.ifs.cache",
     "precision": "default",
     "query": "SELECT mean(\"l2_meta_read_hit\")/ mean(\"l2_meta_read_start\") FROM \"node.ifs.cache\" WHERE \"cluster\" =~ /^$cluster$/ AND \"node\" =~ /^$node$/ AND $timeFilter GROUP BY time($interval), \"node\", \"cluster\" fill(null)",
     "select": [
      [
       { "params": [ "l1_data_read_hit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ],
      [
       { "params": [ "l1_data_read_start" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    }
   ]
  },
  { "title": "L3 Metadata Cache by node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "L3 Metadata hits by node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "L3 Read hits - node $tag_node",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.ifs.cache",
     "precision": "default",
     "query": "SELECT mean(\"l3_meta_read_hit\")/ mean(\"l3_meta_read_start\") FROM \"node.ifs.cache\" WHERE \"cluster\" =~ /^$cluster$/ AND \"node\" =~ /^$node$/ AND $timeFilter GROUP BY time($interval), \"node\", \"cluster\" fill(null)",
     "select": [
      [
       { "params": [ "l1_data_read_hit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ],
      [
       { "params": [ "l1_data_read_start" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    }
   ]
  },
  { "title": "Disk IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Disk IO for $cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Writes",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster.disk.bytes.in.rate",
     "precision": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "Reads",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster.disk.bytes.out.rate",
     "precision": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com",
     "transform": "none"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Max Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "$tag_op_name ($tag_class_name)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "class_name" ], "type": "tag" },
      { "params": [ "op_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster.protostats.hdfs",
     "query": "SELECT mean(\"time_avg\")  / 1000 FROM \"cluster.protostats.$protocol\" WHERE \"cluster\" =~ /^$cluster$/ AND $timeFilter GROUP BY time($interval), \"class_name\",  \"op_name\" fill(null)",
     "select": [
      [
       { "params": [ "time_max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com"
    }
   ]
  }
 ]
}