{
 "title": "Per Node Protocol Stats",
 "tags": [
  "isilon",
  "node"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "show tag values with key = \"cluster\""
   },
   {
    "name": "node",
    "label": "Node",
    "query": "show tag values with key = \"node\" where \"cluster\" =~ /^$cluster/"
   },
   { "name": "protocol", "label": "Protocol", "query": "nfs,smb2" }
  ]
 },
 "panels": [
  {
   "title": "Protocol Latency by Node- $cluster",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms", "label": "Latency" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Node $tag_node",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.protostats.$protocol",
     "select": [
      [
       { "params": [ "time_avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com"
    }
   ]
  },
  {
   "title": "CPU Utilization by Node- $cluster",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit", "label": "CPU Utilization" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Interrupt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "node.cpu.intr.avg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com"
    },
    {
     "alias": "System",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "node.cpu.sys.avg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "User",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "node.cpu.user.avg",
     "query": "SELECT mean(\"value\")  / 1000 FROM \"node.cpu.user.avg\" WHERE (\"cluster\" =~ /^$cluster$/ AND \"node\" =~ /^$node$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "Idle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "node.cpu.idle.avg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Per Node NFS Connections - $cluster",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "repeat": "cluster",
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Node $tag_node Active",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.clientstats.active.$protocol",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com"
    }
   ]
  },
  {
   "title": "Operation Counts Per Second  by Node - $cluster",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "repeat": "cluster",
   "yaxes": [
    { "format": "ops", "label": "Operations/Sec" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Node $tag_node",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.protostats.$protocol",
     "select": [
      [
       { "params": [ "op_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com"
    }
   ]
  },
  {
   "title": "Operation Mix by Node - $cluster",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "ops", "label": "Operations/Sec" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "$tag_op_name ($tag_class_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "op_name" ], "type": "tag" },
      { "params": [ "class_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.protostats.$protocol",
     "select": [
      [
       { "params": [ "op_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com"
    },
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.protostats.$protocol",
     "select": [
      [
       { "params": [ "op_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Operation Latency by Node - $cluster",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "ms", "label": "Op Latency" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "$tag_op_name ($tag_class_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "op_name" ], "type": "tag" },
      { "params": [ "class_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node.protostats.$protocol",
     "select": [
      [
       { "params": [ "time_avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ],
     "templatedHost": "nr-hdp.hdfs.demo.west.isilon.com"
    }
   ]
  }
 ]
}